import streamlit as st
import pickle
import os

st.set_page_config(
    page_title="African Language Text Detector",
    page_icon="magnifying glass",
    layout="centered"
)

@st.cache_resource
@st.cache_resource
def load_models():
    model_dir = os.path.join(os.path.dirname(__file__), "..", "models")
    
    with open(os.path.join(model_dir, "vectorizer_tf.pkl"),    "rb") as f: vec_tf    = pickle.load(f)
    with open(os.path.join(model_dir, "classifier_tf.pkl"),    "rb") as f: clf_tf    = pickle.load(f)
    with open(os.path.join(model_dir, "vectorizer_tfidf.pkl"), "rb") as f: vec_tfidf = pickle.load(f)
    with open(os.path.join(model_dir, "classifier_tfidf.pkl"), "rb") as f: clf_tfidf = pickle.load(f)
    
    return vec_tf, clf_tf, vec_tfidf, clf_tfidf

st.title("African Language Text Detector")
st.markdown("**COS 760 NLP Research Project**")
st.markdown("Detects whether text in Yoruba, isiZulu, or Swahili was written by a human or generated by AI.")
st.divider()

col1, col2 = st.columns(2)
with col1:
    language = st.selectbox("Language of the text", ["Yoruba", "isiZulu", "Swahili", "Unknown"])
with col2:
    model_choice = st.selectbox("Model to use", ["CountVectorizer (recommended)", "TF-IDF"])

text_input = st.text_area(
    "Paste your text here",
    height=220,
    placeholder="Paste Yoruba, isiZulu, or Swahili text here to analyse it..."
)

if st.button("Analyse", type="primary", use_container_width=True):
    if not text_input.strip():
        st.warning("Please paste some text before clicking Analyse.")
    else:
        if model_choice == "CountVectorizer (recommended)":
            vec, clf = vec_tf, clf_tf
        else:
            vec, clf = vec_tfidf, clf_tfidf

        X     = vec.transform([text_input])
        pred  = clf.predict(X)[0]
        proba = clf.predict_proba(X)[0]

        human_pct   = round(proba[0] * 100, 1)
        machine_pct = round(proba[1] * 100, 1)

        st.divider()
        st.subheader("Results")

        col_h, col_m = st.columns(2)
        with col_h:
            st.metric("Human-written confidence", f"{human_pct}%")
            st.progress(proba[0])
        with col_m:
            st.metric("AI-generated confidence", f"{machine_pct}%")
            st.progress(proba[1])

        st.divider()
        if pred == 0:
            st.success(f"Verdict: HUMAN-WRITTEN — {human_pct}% confidence")
        else:
            st.error(f"Verdict: AI-GENERATED — {machine_pct}% confidence")

        with st.expander("Text statistics"):
            words  = text_input.split()
            sents  = [s for s in text_input.split('.') if s.strip()]
            unique = len(set(w.lower() for w in words))
            st.write(f"- Words: **{len(words)}**")
            st.write(f"- Sentences: **{len(sents)}**")
            st.write(f"- Unique words: **{unique}** ({round(unique / max(len(words),1) * 100)}% diversity)")
            st.write(f"- Avg sentence length: **{round(len(words) / max(len(sents),1), 1)} words**")
            st.write(f"- Model: **{model_choice}**")
            st.write(f"- Language: **{language}**")

st.divider()
st.caption("Sithembisiso · Thabang · Edwin")
